# .github/workflows/handle-dispatch.yaml
name: Receber atualização de Chart.yaml


on:
  repository_dispatch:
    types: [update-helm-version]
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump event payload
        run: |
          jq . "$GITHUB_EVENT_PATH"
