# .github/workflows/handle-dispatch.yaml
name: Atualizar Versão
on:
  repository_dispatch:
    types: [update-helm-version]

  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Criar branch e atualizar Chart.yaml
        run: |
          BRANCH="update-helm-${{ github.event.client_payload.new_version }}"
          git checkout -b $BRANCH

          sed -i "s/^version: .*/version: ${{ github.event.client_payload.new_version }}/" "${{ github.event.client_payload.chart_path }}"

          git add "${{ github.event.client_payload.chart_path }}"
          git commit -m "Update Helm chart version to ${{ github.event.client_payload.new_version }}"
          git push origin $BRANCH

      - uses: actions/create-github-app-token@v1
        id: app-token
        with: 
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ansible-test
            infra-test
      - name: Create repository dispatch event
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api repos/teste-gitops/infra-test/pulls \
          --method POST \
          --field title='Atualiza versão da app: ${{ github.event.client_payload.new_version }}' \
          --field head="update-helm-${{ github.event.client_payload.new_version }}" \
          --field base='main' \
          --field body='Atualização da versão da aplicação para ${{ github.event.client_payload.new_version }}'
