# .github/workflows/reusable-update.yaml
name: Atualiza Chart.yaml (reutilizável)

on:
  workflow_call:
    inputs:
      new_version:
        required: true
        type: string
      chart_path:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório de infra
        uses: actions/checkout@v3
        with:
          repository: euprogramador/infra-test
          ref: main
          token: ${{ github.token }}
          persist-credentials: false

      - name: Atualizar Chart.yaml e criar PR
        run: |
          VERSION="${{ inputs.new_version }}"
          FILE="${{ inputs.chart_path }}"
          BRANCH="update-chart-$VERSION"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          sed -i "s/^version: .*/version: $VERSION/" "$FILE"
          git add "$FILE"
          git commit -m "Atualiza Chart para versão $VERSION"
          git push origin "$BRANCH"

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "update-chart-${{ inputs.new_version }}"
          title: "Atualiza Chart para versão ${{ inputs.new_version }}"
          body: "PR automático via workflow_call"
